/*
 * package com.demo.exception.handler.revice;
 * 
 * public class ExceptionDemo1 {
 * 
 * public static void main(String[] args) {
 * 
 * 
 * try { int result = 1/0; System.out.println(result); } catch (Exception e) {
 * System.out.println("Exception"); } catch (RuntTimeException e) {
 * System.out.println("RunTime"); } }
 * 
 * }
 */